INSERT INTO TRAINERS VALUES (1, 'John', 'Nemkov', 'Anatolyevich', TRUE, CURRENT_DATE(), 30000);
INSERT INTO TRAINERS VALUES (2, 'Ivan', 'Kov', 'Anatolyevich', TRUE, CURRENT_DATE(), 50000);


INSERT INTO GYM VALUES (1,'Gymnasium', 1);
INSERT INTO GYM VALUES (2,'Plastilin',2);