CREATE TABLE TRAINERS (
ID INT AUTO_INCREMENT  PRIMARY KEY,
NAME VARCHAR(250) NOT NULL,
SURNAME VARCHAR(250) NOT NULL,
PATRONYMIC VARCHAR(250) NOT NULL,
GENDER BOOLEAN DEFAULT FALSE,
BIRTH DATE NOT NULL,
SALARY INT NOT NULL
);

CREATE TABLE GYMS (
ID INT AUTO_INCREMENT  PRIMARY KEY,
CLUBNAME VARCHAR(250) NOT NULL,
TRAINERID INT NOT NULL
);